### ISSUE TITLE
filter sometimes passes all objects when condition is not met

### ISSUE THREAD

**Issue by shartse** [delphix/sdb#151]
**Expected Behavior**
When using a filter with a `Locator`, I would expect that only the objects matching the filter are returned, for example:
```
sdb> slabs | filter obj.name == "kmalloc-512" | slabs | count
(unsigned long long)1
```
If no objects match, I would expect no output. 

**Actual Behavior**
Instead, all objects pass through the filter:
```
sdb> slabs | filter obj.name == "bogus" | slabs | count
(unsigned long long)132
```
Interestingly, this does not reproduce with a simple base case of filter:
```
sdb> echo 0x0  0x2 | filter obj == 1
>
sdb> echo 0x0  0x2 0x1 | filter obj == 1
(void *)0x1
```

**Comment by shartse** [comment]
I think I know what the issue is - passing the empty results of `filter` to another `Locator` causes the `Locator` to go ahead and re-locate everything.

You can see the difference here:

```
sdb> slabs | filter obj.name == "bogus" | slabs | count
(unsigned long long)132
sdb> slabs | filter obj.name == "bogus" | count
(unsigned long long)0
```

**Comment by ahrens** [comment]
I see, so we're calling the `no_input()` method since there are no objects passed in.  I wonder if that's really the right design, or if we should be doing `no_input()` only if this is the first thing in the pipeline.  Would that break any useful workflows?

**Comment by sdimitro** [comment]
As far as I can tell there shouldn't be any workflows that depend on this currently. I also have a hard time thinking of an example consumer command that needs to Locate data mid-pipeline with no input passed to it from a previous pipeline stage (e.g. "if I'm not passed any input I will locate data for you by default").

I'd be ok with making the Locator only using no_input if it is in the beginning of the pipeline (and maybe have a ConditionalLocator in the future if the need arises)
