### ISSUE TITLE
drgn requires newer libelf_dev, breaks CI

### ISSUE THREAD

**Issue by PaulZ-98** [delphix/sdb#268]
** Expected Behavior**
drgn configure step should succeed

** Actual Behavior**
drgn configure step errors because libelf version is not 0.176

**Steps To Reproduce the Problem**
Check-in a PR to get a CI run

**Screenshots**
Run ./.github/scripts/install-drgn.sh
...
+ git clone https://github.com/osandov/drgn.git
Cloning into 'drgn'...
+ cd drgn
+ python3 setup.py install
... <snip>
checking for elfutils... no
configure: error: Package requirements (libelf >= 0.176 libdw >= 0.176) were not met:
Requested 'libelf >= 0.176' but version of libelf is 0.170
You may find new versions of libelf at http://elfutils.org/
Requested 'libdw >= 0.176' but version of libdw is 0.170
You may find new versions of libdw at http://elfutils.org/

**Additional Context**
breaking change to drgn
https://github.com/osandov/drgn/commit/4c5c5f384232d1b5b92fe6b2ab424de56060293d

libelf / libdw version 0.176 is not available in Ubuntu 18/bionic, so CI needs to either move up to newer Ubuntu or find an alternative installation of necessary libelf / libdw version.  If I checkout an earlier version of drgn in install-drgn.sh the problem is avoided:

git clone https://github.com/osandov/drgn.git
cd drgn
git checkout -b drgn_february 0a6aaaae5d31ed142448f8220e208d65478ec80d
python3 setup.py install

**Comment by sdimitro** [comment]
I opened the following PR which should fix our issues once it gets integrated in drgn: https://github.com/osandov/drgn/pull/93
