### ISSUE TITLE
Documentation for spl_cache is incorrect

### ISSUE THREAD

**Issue by ryao** [delphix/sdb#295]
`help spl_cache` uses `spl_kmem_caches | filter obj.skc_name == "ddt_cache" | spl_cache` as an example, which is broken:

```
sdb> spl_kmem_caches | filter obj.skc_name == "ddt_cache" | spl_cache
usage: filter [-h] expr
filter: error: unrecognized arguments: == ddt_cache
```

It is missing single quotes. `spl_kmem_caches | filter 'obj.skc_name == "ddt_cache"' | spl_cache` works.

**Comment by sdimitro** [comment]
Fixed in 6.0/stage. Should propagate to master soon
